/**
 * PlayerReportScreen — the season development report card.
 * Minutes, attendance, stats, and the coach's rating trend + notes in one
 * shareable page. Data arrives via params (assembled by PlayerProfileScreen).
 */
import React from 'react';
import { SafeAreaView, ScrollView, Share, Text, TouchableOpacity, View } from 'react-native';
import { useRoute, type RouteProp } from '@react-navigation/native';
import { B } from '../../constants/brand';

export type PlayerReportParams = {
  playerName: string;
  teamName?: string;
  seasonLabel?: string;
  stats: { appearances: number; goals: number; assists: number; yellowCards: number; redCards: number };
  minutes?: { totalMinutes: number; appearances: number; starts: number; avgMinutes: number } | null;
  attendance?: { attended: number; total: number } | null;
  ratings: Array<{ rating: number; note?: string; matchDateISO?: string; opponent?: string; coachName?: string }>;
};

type Params = { PlayerReport: PlayerReportParams };

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={{
      flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10,
      borderBottomWidth: 1, borderBottomColor: '#f3f4f6',
    }}>
      <Text style={{ fontSize: 14, color: '#6b7280' }}>{label}</Text>
      <Text style={{ fontSize: 14, fontWeight: '800', color: '#111', fontVariant: ['tabular-nums'] }}>{value}</Text>
    </View>
  );
}

export default function PlayerReportScreen() {
  const route = useRoute<RouteProp<Params, 'PlayerReport'>>();
  const { playerName, teamName, seasonLabel, stats, minutes, attendance, ratings } = route.params;

  const chronological = [...ratings].sort((a, b) =>
    (a.matchDateISO || '').localeCompare(b.matchDateISO || ''));
  const avgRating = ratings.length
    ? Math.round((ratings.reduce((s, r) => s + r.rating, 0) / ratings.length) * 10) / 10
    : null;
  const attendancePct = attendance && attendance.total > 0
    ? Math.round((attendance.attended / attendance.total) * 100)
    : null;

  const onShare = async () => {
    const lines = [
      `${playerName} — Season Report${teamName ? ` · ${teamName}` : ''}${seasonLabel ? ` · ${seasonLabel}` : ''}`,
      ``,
      `Appearances: ${stats.appearances} · Goals: ${stats.goals} · Assists: ${stats.assists}`,
      minutes ? `Minutes: ${minutes.totalMinutes}' (avg ${minutes.avgMinutes}'/game, ${minutes.starts} starts)` : '',
      attendancePct != null ? `Training attendance: ${attendance!.attended}/${attendance!.total} (${attendancePct}%)` : '',
      avgRating != null ? `Average coach rating: ${avgRating}/5 over ${ratings.length} matches` : '',
      ``,
      `Generated by Formavo ⚽`,
    ].filter((l) => l !== '');
    try { await Share.share({ message: lines.join('\n') }); } catch { /* cancelled */ }
  };

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: B.surface }}>
      <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 40 }}>
        {/* Header */}
        <View style={{ backgroundColor: B.navy, borderRadius: 16, padding: 20 }}>
          <Text style={{ fontSize: 11, fontWeight: '800', letterSpacing: 1.2, color: B.greenBright }}>
            SEASON REPORT
          </Text>
          <Text style={{ fontSize: 24, fontWeight: '900', color: '#fff', marginTop: 6 }}>{playerName}</Text>
          {(teamName || seasonLabel) && (
            <Text style={{ fontSize: 13, color: 'rgba(255,255,255,0.6)', marginTop: 3 }}>
              {[teamName, seasonLabel].filter(Boolean).join(' · ')}
            </Text>
          )}
        </View>

        {/* Numbers */}
        <View style={s.card}>
          <Text style={s.cardTitle}>SEASON NUMBERS</Text>
          <Row label="Appearances" value={String(stats.appearances)} />
          <Row label="Goals · Assists" value={`${stats.goals} · ${stats.assists}`} />
          {minutes && minutes.appearances > 0 && (
            <>
              <Row label="Minutes played" value={`${minutes.totalMinutes}'`} />
              <Row label="Average per game" value={`${minutes.avgMinutes}'`} />
              <Row label="Starts" value={String(minutes.starts)} />
            </>
          )}
          {attendancePct != null && (
            <Row label="Training attendance" value={`${attendance!.attended}/${attendance!.total} (${attendancePct}%)`} />
          )}
          {(stats.yellowCards > 0 || stats.redCards > 0) && (
            <Row label="Cards" value={`${stats.yellowCards}🟨 ${stats.redCards > 0 ? `${stats.redCards}🟥` : ''}`} />
          )}
        </View>

        {/* Rating trend */}
        {chronological.length > 0 && (
          <View style={s.card}>
            <Text style={s.cardTitle}>
              COACH RATINGS{avgRating != null ? `  ·  avg ${avgRating}/5` : ''}
            </Text>
            <View style={{ flexDirection: 'row', alignItems: 'flex-end', gap: 6, marginTop: 12, height: 64 }}>
              {chronological.slice(-14).map((r, i) => (
                <View key={i} style={{ flex: 1, alignItems: 'center', gap: 4 }}>
                  <View style={{
                    width: '100%', maxWidth: 26,
                    height: 10 + (r.rating / 5) * 44,
                    borderRadius: 5,
                    backgroundColor: r.rating >= 4 ? '#22c55e' : r.rating >= 3 ? '#a3e635' : '#f59e0b',
                  }} />
                  <Text style={{ fontSize: 9, color: '#9ca3af' }}>{r.rating}</Text>
                </View>
              ))}
            </View>
            <Text style={{ fontSize: 11, color: '#c7c7cc', marginTop: 6 }}>
              Oldest → most recent{chronological.length > 14 ? ` (last 14 of ${chronological.length})` : ''}
            </Text>
          </View>
        )}

        {/* Coach notes */}
        {chronological.filter((r) => r.note?.trim()).length > 0 && (
          <View style={s.card}>
            <Text style={s.cardTitle}>COACH NOTES</Text>
            {chronological.filter((r) => r.note?.trim()).map((r, i) => (
              <View key={i} style={{ marginTop: 12 }}>
                <Text style={{ fontSize: 12, color: '#9ca3af' }}>
                  {r.opponent ? `vs ${r.opponent}` : 'Match'}{r.matchDateISO ? ` · ${r.matchDateISO.substring(0, 10)}` : ''} · {r.rating}★
                </Text>
                <Text style={{ fontSize: 14, color: '#111', marginTop: 3, lineHeight: 20 }}>"{r.note!.trim()}"</Text>
              </View>
            ))}
          </View>
        )}

        <TouchableOpacity
          onPress={onShare}
          style={{ backgroundColor: '#111', borderRadius: 14, paddingVertical: 15, alignItems: 'center', marginTop: 18 }}
        >
          <Text style={{ color: '#fff', fontWeight: '800', fontSize: 15 }}>Share report</Text>
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}

const s = {
  card: {
    backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e5e7eb',
    padding: 16, marginTop: 14,
  } as const,
  cardTitle: { fontSize: 12, fontWeight: '800', color: '#9ca3af', letterSpacing: 0.6 } as const,
};
