/**
 * TryoutDetailScreen — evaluate candidates fast: quick-add by name/number,
 * tap 1–5 to rate, tag keep/maybe/pass, share the shortlist.
 */
import React, { useEffect, useMemo, useState } from 'react';
import {
  Alert,
  KeyboardAvoidingView,
  Platform,
  SafeAreaView,
  ScrollView,
  Share,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { useRoute, type RouteProp } from '@react-navigation/native';
import {
  addCandidate,
  listenCandidates,
  removeCandidate,
  updateCandidate,
  type Candidate,
  type CandidateTag,
} from '../../services/tryoutService';

type Params = { TryoutDetail: { clubId: string; tryoutId: string; tryoutName?: string } };

const TAGS: { value: Exclude<CandidateTag, null>; label: string; color: string }[] = [
  { value: 'keep', label: 'Keep', color: '#16a34a' },
  { value: 'maybe', label: 'Maybe', color: '#f59e0b' },
  { value: 'pass', label: 'Pass', color: '#9ca3af' },
];

export default function TryoutDetailScreen() {
  const route = useRoute<RouteProp<Params, 'TryoutDetail'>>();
  const { clubId, tryoutId, tryoutName } = route.params;

  const [candidates, setCandidates] = useState<Candidate[]>([]);
  const [newName, setNewName] = useState('');
  const [newNumber, setNewNumber] = useState('');

  useEffect(() => listenCandidates(clubId, tryoutId, setCandidates), [clubId, tryoutId]);

  const onAdd = async () => {
    if (!newName.trim()) return;
    try {
      await addCandidate(clubId, tryoutId, newName, newNumber);
      setNewName('');
      setNewNumber('');
    } catch (e: any) {
      Alert.alert('Add failed', e?.message ?? 'Unknown error');
    }
  };

  const counts = useMemo(() => ({
    keep: candidates.filter((c) => c.tag === 'keep').length,
    maybe: candidates.filter((c) => c.tag === 'maybe').length,
    pass: candidates.filter((c) => c.tag === 'pass').length,
  }), [candidates]);

  const onShare = async () => {
    const group = (tag: CandidateTag, title: string) => {
      const rows = candidates.filter((c) => c.tag === tag);
      if (!rows.length) return '';
      return `${title}:\n${rows.map((c) =>
        `  ${c.name}${c.number ? ` #${c.number}` : ''}${c.rating ? ` — ${c.rating}/5` : ''}`).join('\n')}\n`;
    };
    const message = [
      `${tryoutName || 'Tryout'} — evaluation summary`,
      ``,
      group('keep', '✅ Keep'),
      group('maybe', '🤔 Maybe'),
      group('pass', 'Pass'),
      `Generated by Formavo ⚽`,
    ].filter(Boolean).join('\n');
    try { await Share.share({ message }); } catch { /* cancelled */ }
  };

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: '#f2f2f7' }}>
      <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}>
        {/* Quick add */}
        <View style={{ flexDirection: 'row', gap: 8, padding: 16, paddingBottom: 8 }}>
          <TextInput
            value={newName}
            onChangeText={setNewName}
            placeholder="Candidate name"
            placeholderTextColor="#9ca3af"
            onSubmitEditing={onAdd}
            returnKeyType="done"
            style={{
              flex: 1, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e5e7eb',
              borderRadius: 12, padding: 11, fontSize: 14, color: '#111',
            }}
          />
          <TextInput
            value={newNumber}
            onChangeText={setNewNumber}
            placeholder="#"
            placeholderTextColor="#9ca3af"
            keyboardType="number-pad"
            style={{
              width: 56, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e5e7eb',
              borderRadius: 12, padding: 11, fontSize: 14, color: '#111', textAlign: 'center',
            }}
          />
          <TouchableOpacity
            onPress={onAdd}
            disabled={!newName.trim()}
            style={{
              backgroundColor: newName.trim() ? '#111' : '#e5e7eb', borderRadius: 12,
              paddingHorizontal: 14, justifyContent: 'center',
            }}
          >
            <Text style={{ color: newName.trim() ? '#fff' : '#9ca3af', fontWeight: '800' }}>Add</Text>
          </TouchableOpacity>
        </View>

        {/* Tally */}
        <View style={{ flexDirection: 'row', gap: 12, paddingHorizontal: 16, paddingBottom: 4 }}>
          <Text style={{ fontSize: 12, fontWeight: '700', color: '#16a34a' }}>✅ {counts.keep} keep</Text>
          <Text style={{ fontSize: 12, fontWeight: '700', color: '#f59e0b' }}>🤔 {counts.maybe} maybe</Text>
          <Text style={{ fontSize: 12, fontWeight: '700', color: '#9ca3af' }}>{counts.pass} pass · {candidates.length} total</Text>
        </View>

        <ScrollView contentContainerStyle={{ padding: 16, paddingTop: 8, paddingBottom: 90 }} keyboardShouldPersistTaps="handled">
          {candidates.length === 0 && (
            <View style={{ backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e5e7eb', padding: 24, alignItems: 'center' }}>
              <Text style={{ fontSize: 14, color: '#9ca3af', textAlign: 'center' }}>
                Add candidates as they check in, then rate as they play.
              </Text>
            </View>
          )}
          {candidates.map((c) => (
            <View key={c.id} style={{
              backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e5e7eb',
              padding: 14, marginBottom: 10,
            }}>
              <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
                <Text style={{ fontSize: 15, fontWeight: '800', color: '#111' }}>
                  {c.name}{c.number ? `  #${c.number}` : ''}
                </Text>
                <TouchableOpacity
                  onPress={() =>
                    Alert.alert('Remove candidate?', c.name, [
                      { text: 'Cancel', style: 'cancel' },
                      { text: 'Remove', style: 'destructive',
                        onPress: () => removeCandidate(clubId, tryoutId, c.id).catch(() => {}) },
                    ])
                  }
                  hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                >
                  <Text style={{ fontSize: 16, color: '#ef4444', fontWeight: '700' }}>×</Text>
                </TouchableOpacity>
              </View>

              <View style={{ flexDirection: 'row', gap: 6, marginTop: 10 }}>
                {[1, 2, 3, 4, 5].map((n) => (
                  <TouchableOpacity
                    key={n}
                    onPress={() => updateCandidate(clubId, tryoutId, c.id, { rating: c.rating === n ? 0 : n }).catch(() => {})}
                    hitSlop={{ top: 6, bottom: 6 }}
                  >
                    <Text style={{ fontSize: 24, color: n <= c.rating ? '#f59e0b' : '#e5e7eb' }}>★</Text>
                  </TouchableOpacity>
                ))}
                <View style={{ flex: 1 }} />
                {TAGS.map((t) => (
                  <TouchableOpacity
                    key={t.value}
                    onPress={() => updateCandidate(clubId, tryoutId, c.id, { tag: c.tag === t.value ? null : t.value }).catch(() => {})}
                    style={{
                      paddingVertical: 5, paddingHorizontal: 10, borderRadius: 10,
                      backgroundColor: c.tag === t.value ? t.color : '#f3f4f6',
                    }}
                  >
                    <Text style={{
                      fontSize: 12, fontWeight: '700',
                      color: c.tag === t.value ? '#fff' : '#6b7280',
                    }}>
                      {t.label}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>
            </View>
          ))}
        </ScrollView>

        {candidates.length > 0 && (
          <View style={{ position: 'absolute', bottom: 20, left: 16, right: 16 }}>
            <TouchableOpacity
              onPress={onShare}
              style={{ backgroundColor: '#111', borderRadius: 14, paddingVertical: 14, alignItems: 'center' }}
            >
              <Text style={{ color: '#fff', fontWeight: '800', fontSize: 15 }}>Share shortlist</Text>
            </TouchableOpacity>
          </View>
        )}
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
